//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioProject.Models.Entity
{
	using System;
	using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class Portfolio
	{
		public int ID { get; set; }
		[Required(ErrorMessage = "Bu alaný boþ geçemezsiniz")]
		public string Title { get; set; }
		[Required(ErrorMessage = "Bu alaný boþ geçemezsiniz")]
		[StringLength(100, ErrorMessage = "Lütfen en fazla 100 karakterlik veri giriþi yapýnýz")]
		public string Image { get; set; }
		public Nullable<System.DateTime> AddDate { get; set; }
	}
}
